name = "pokemon-auth"
assets = [
  ".env",
  ".sqlx/*",
  "configuration/base.toml",
  "configuration/development.toml",
  "configuration/production.toml",
] # Declare ignored files that should be included in deployment:
